### ISSUE TITLE
New templates should not have a random blank included by default

### ISSUE THREAD

**Issue by trife** [PhenoApps/Coordinate#23]

**Comment by chaneylc** [comment]
This is fixed in #48

**Comment by trife** [comment]
I'm still seeing this behavior on `develop`. Create new template, leave exclude unchanged, grids created from that template have a random blank.
